.PHONY: all clean

all:
	$(MAKE) -C Src/MCAL
	$(MAKE) -C Src/ECU_Abstraction
	$(MAKE) -C Src/Services

clean:
	$(MAKE) -C Src/MCAL clean
	$(MAKE) -C Src/ECU_Abstraction clean
	$(MAKE) -C Src/Services clean
